//
// Created by nhatminh2947 on 10/8/19.
//

#ifndef MACHINE_LEARNING_COURSE_NAIVEBAYESCLASSIFIER_H
#define MACHINE_LEARNING_COURSE_NAIVEBAYESCLASSIFIER_H


class NaiveBayesClassifier {

};


#endif //MACHINE_LEARNING_COURSE_NAIVEBAYESCLASSIFIER_H
